/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.awt.Color;

/**
 *
 * @author RonaldDavidMartinezM
 */
public class Screen extends javax.swing.JFrame {

    /**
     * Creates new form Screen
     */
    public Screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        cityphto = new javax.swing.JLabel();
        minlogo = new javax.swing.JLabel();
        iniciosesion = new javax.swing.JLabel();
        Usuario1 = new javax.swing.JLabel();
        User_textfield = new javax.swing.JTextField();
        User_Separator = new javax.swing.JSeparator();
        Contraseña = new javax.swing.JLabel();
        Pass = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        loginBtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMinimumSize(new java.awt.Dimension(800, 500));
        bg.setPreferredSize(new java.awt.Dimension(800, 500));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo.png"))); // NOI18N
        bg.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 270, -1));

        titulo.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Energy Wise");
        bg.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 270, -1));

        cityphto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/city.png"))); // NOI18N
        cityphto.setText("jLabel1");
        cityphto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(cityphto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 280, 500));

        minlogo.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        minlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/favicon.png"))); // NOI18N
        minlogo.setText("LOGO");
        bg.add(minlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        iniciosesion.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        iniciosesion.setText("INICIAR SESIÓN");
        bg.add(iniciosesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        Usuario1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Usuario1.setText("USUARIO ");
        bg.add(Usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        User_textfield.setForeground(new java.awt.Color(204, 204, 204));
        User_textfield.setText("Ingrese su usuario");
        User_textfield.setBorder(null);
        User_textfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                User_textfieldMousePressed(evt);
            }
        });
        User_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_textfieldActionPerformed(evt);
            }
        });
        bg.add(User_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 430, 30));

        User_Separator.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(User_Separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 410, 10));

        Contraseña.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Contraseña.setText("CONTRASEÑA");
        bg.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        Pass.setForeground(new java.awt.Color(204, 204, 204));
        Pass.setText(".....");
        Pass.setBorder(null);
        Pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PassMousePressed(evt);
            }
        });
        Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassActionPerformed(evt);
            }
        });
        bg.add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 410, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 410, 10));

        loginBtn.setBackground(new java.awt.Color(51, 153, 255));
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel2.setText("INGRESAR");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout loginBtnLayout = new javax.swing.GroupLayout(loginBtn);
        loginBtn.setLayout(loginBtnLayout);
        loginBtnLayout.setHorizontalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBtnLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        loginBtnLayout.setVerticalGroup(
            loginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginBtnLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18))
        );

        bg.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassActionPerformed

    private void User_textfieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_textfieldMousePressed
        if(User_textfield.getText().equals("Ingrese su nombre de usuario")){
        User_textfield.setText("");
        User_textfield.setForeground(Color.black);
        }
        if(String.valueOf(Pass.getPassword()).isEmpty()){
        Pass.setText("*****");
        Pass.setForeground(Color.gray);
        }
     
        
        
        
    }//GEN-LAST:event_User_textfieldMousePressed

    private void User_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User_textfieldActionPerformed

    private void PassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassMousePressed
        if(String.valueOf(Pass.getPassword()).equals("*****")){
        User_textfield.setText("Ingrese su nombre de usuario");
        User_textfield.setForeground(Color.gray);
        }
        if(User_textfield.getText().isEmpty()){
        Pass.setText("");
        Pass.setForeground(Color.black);
        }
       
    }//GEN-LAST:event_PassMousePressed

    private void loginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseEntered
       loginBtn.setBackground(new Color(51,153,255));
        
    }//GEN-LAST:event_loginBtnMouseEntered

    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseExited
        loginBtn.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_loginBtnMouseExited

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
       javax.swing.JOptionPane.showMessageDialog(this,"Intento de login con los datos \nUsuario: "+ User_textfield.getText()+"\nContraseña: " + String.valueOf(Pass.getPassword()),"Login", javax.swing.JOptionPane.INFORMATION_MESSAGE); ;
    }//GEN-LAST:event_loginBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contraseña;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JSeparator User_Separator;
    private javax.swing.JTextField User_textfield;
    private javax.swing.JLabel Usuario1;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel cityphto;
    private javax.swing.JLabel iniciosesion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel loginBtn;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel minlogo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
